# https://docs.influxdata.com/influxdb/v2.1/api/
- name: login
  uri:
    method: POST
    url: '{{ influxdb_v2_user_url }}/api/v2/signin'
    force_basic_auth: yes
    # naming `url_{username,password}` based on
    # https://web.archive.org/web/20211226100248/https://docs.ansible.com/ansible/latest/collections/community/grafana/grafana_datasource_module.html#parameter-url_username
    url_username: '{{ influxdb_v2_user_url_username }}'
    url_password: '{{ influxdb_v2_user_url_password }}'
    status_code: 204
  register: _login
- name: check if user exists
  uri:
    method: GET
    url: '{{ influxdb_v2_user_url }}/api/v2/users?name={{ influxdb_v2_user_name | urlencode }}'
    headers: {Cookie: '{{ _login.cookies_string }}'}
    status_code: [200, 404]
  register: _users
- assert:
    that: _users.status == 404 or (_users.json.users | length) == 1
- name: create user
  uri:
    method: POST
    url: '{{ influxdb_v2_user_url }}/api/v2/users'
    headers: {Cookie: '{{ _login.cookies_string }}'}
    body_format: json
    body:
      name: '{{ influxdb_v2_user_name }}'
    status_code: 201
  changed_when: true
  when: _users.status == 404
  register: _user
- &fetch_authorizations_task
  name: fetch authorizations
  uri:
    method: GET
    url: '{{ influxdb_v2_user_url }}/api/v2/authorizations?user={{ influxdb_v2_user_name | urlencode }}'
    headers: {Cookie: '{{ _login.cookies_string }}'}
  register: _authorizations
  when: >-
    influxdb_v2_user_fetch_authorizations
    or influxdb_v2_user_authorizations_overwrite
    or influxdb_v2_user_authorizations_append
- &set_return_values_task
  name: set return values
  set_fact:
    influxdb_v2_user_id: >-
      {{ _users.json.users[0].id if (_user.skipped | default(False)) else _user.json.id }}
    influxdb_v2_user_authorizations: >-
      {{ _authorizations.json.authorizations if influxdb_v2_user_fetch_authorizations else none }}
    influxdb_v2_user_url_cookies_string: '{{ _login.cookies_string }}'
- name: delete excess authorizations
  vars:
    _authorization_config:
      organization_id: '{{ item.orgID }}'
      permissions: '{{ item.permissions }}'
  uri:
    method: DELETE
    url: '{{ influxdb_v2_user_url }}/api/v2/authorizations/{{ item.id }}'
    headers: {Cookie: '{{ _login.cookies_string }}'}
    status_code: 204
  changed_when: true
  when: _authorization_config not in influxdb_v2_user_authorizations_overwrite
  loop: >-
    {{ _authorizations.json.authorizations
       if influxdb_v2_user_authorizations_overwrite else [] }}
  register: _delete_authorizations
- name: create missing authorizations
  vars:
    _authorizations_filtered: >-
      {{ _authorizations.json.authorizations
         | json_query('[*].{
             userID: userID, orgID: orgID, permissions: permissions, status: status
           }') }}
    _authorization:
      userID: '{{ influxdb_v2_user_id }}'
      orgID: '{{ item.organization_id }}'
      permissions: '{{ item.permissions }}'
      status: active
  uri:
    method: POST
    url: '{{ influxdb_v2_user_url }}/api/v2/authorizations'
    headers: {Cookie: '{{ _login.cookies_string }}'}
    body_format: json
    body: "{{ _authorization | combine({'description': 'created via ansible'}) }}"
    status_code: 201
  changed_when: true
  when: _authorization not in _authorizations_filtered
  loop: >-
    {{ (influxdb_v2_user_authorizations_overwrite or [])
       + (influxdb_v2_user_authorizations_append or []) }}
  register: _create_authorizations
- <<: *fetch_authorizations_task
  when: &refetch_authorizations
    _delete_authorizations.changed or _create_authorizations.changed
- <<: *set_return_values_task
  when: *refetch_authorizations
